/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chipchip.livestreamudp.Server;

import com.chipchip.livestreamudp.Client.LiveStreamFrm;
import com.chipchip.livestreamudp.Server.model.Client;
import com.chipchip.livestreamudp.Server.model.ClientHandlerTCP;
import com.chipchip.livestreamudp.Server.model.Command;
import com.chipchip.livestreamudp.Server.model.GroupLive;
import com.chipchip.livestreamudp.Server.model.StreamGroup;
import java.awt.Button;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class MainFrm extends javax.swing.JFrame {
    
    private static int PORT_COMMAND = 12345;
    private static int PORT_STREAMING = 12346;
    private ServerSocket commandSocket = null;
    private DatagramSocket streamingSocket = null;
    public static List<Client> clients = null;
    public static List<StreamGroup> streamers = null;
    private boolean running = false;
    
    private static String START_SERVER = "Start Server";
    private static String STOP_SERVER = "Stop Server";
    
    ByteArrayInputStream byteArrayInputStream = null;
    ByteArrayOutputStream byteArrayOutputStream = null;
    DatagramPacket sendPacket = null;
    DatagramPacket recivePacket = null;
    static byte[] imageData = new byte[65507];
    
    private Thread tcpThread = null;
    private Thread udpThread = null;
    
    public void initServer(){
        if(tcpThread!=null){
            if(tcpThread.isAlive()){
                tcpThread.stop();
                tcpThread = null;
            }
        }
        if(udpThread!=null){
            if(udpThread.isAlive()){
                udpThread.stop();
                udpThread = null;
            }
        }
        commandSocket = null;
        streamingSocket = null;
        clients = new ArrayList<>();
        streamers = new ArrayList<>();
        running = false;
        removeAllButton();
        this.lbClients.setText("0");
        this.lbDownload.setText("0");
        this.lbUpload.setText("0");
        this.lbLineD.setText("0");
        this.lbLineU.setText("0");
    }

    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
        this.pnLiveStream.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        initServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbLineD = new javax.swing.JLabel();
        lbLineU = new javax.swing.JLabel();
        lbClients = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbDownload = new javax.swing.JLabel();
        lbUpload = new javax.swing.JLabel();
        pnLiveStream = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnAction.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnAction.setText("Start Server");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        txtLogs.setEditable(false);
        txtLogs.setColumns(20);
        txtLogs.setRows(5);
        jScrollPane1.setViewportView(txtLogs);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Server Logs:");

        jLabel2.setText("Download:");

        jLabel3.setText("Upload:");

        jLabel4.setForeground(new java.awt.Color(200, 0, 0));
        jLabel4.setText("mb/s");

        jLabel5.setForeground(new java.awt.Color(200, 0, 0));
        jLabel5.setText("mb/s");

        jLabel6.setForeground(new java.awt.Color(0, 200, 0));
        jLabel6.setText("lines");

        jLabel7.setForeground(new java.awt.Color(0, 200, 0));
        jLabel7.setText("lines");

        lbLineD.setForeground(new java.awt.Color(0, 200, 0));
        lbLineD.setText("0");

        lbLineU.setForeground(new java.awt.Color(0, 200, 0));
        lbLineU.setText("0");

        lbClients.setForeground(new java.awt.Color(0, 0, 200));
        lbClients.setText("0");

        jLabel11.setForeground(new java.awt.Color(0, 0, 200));
        jLabel11.setText("clients");

        lbDownload.setForeground(new java.awt.Color(200, 0, 0));
        lbDownload.setText("0");

        lbUpload.setForeground(new java.awt.Color(200, 0, 0));
        lbUpload.setText("0");

        javax.swing.GroupLayout pnLiveStreamLayout = new javax.swing.GroupLayout(pnLiveStream);
        pnLiveStream.setLayout(pnLiveStreamLayout);
        pnLiveStreamLayout.setHorizontalGroup(
            pnLiveStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnLiveStreamLayout.setVerticalGroup(
            pnLiveStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(lbClients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDownload)
                    .addComponent(lbUpload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLineU)
                    .addComponent(lbLineD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(pnLiveStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbClients)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbLineD)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbLineU)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbDownload)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbUpload))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addGap(30, 30, 30)
                        .addComponent(pnLiveStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
        if(btnAction.getText().equals(START_SERVER)){
            enableServer();
        }
        else{
            closeServer();
        }
    }//GEN-LAST:event_btnActionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.closeServer();
    }//GEN-LAST:event_formWindowClosing

    //FUNTION
    private void enableServer() {
        initServer();
        this.btnAction.setText(STOP_SERVER);
        try{
            this.running = true;
            commandSocket = new ServerSocket(PORT_COMMAND);
            tcpThread = new Thread(this::watchDog);
            tcpThread.setName("WatchDog_Thread");
            tcpThread.start();
            streamingSocket = new DatagramSocket(PORT_STREAMING);
            udpThread = new Thread(this::watchCat);
            udpThread.setName("WatchCat_Thread");
            udpThread.start();
            log("[*]Server listening....");
        }catch(IOException ex){
            log("[#]Error:Server can't start!");
            closeServer();
        }
    }
    
    private void watchDog() {
        log("..."+Thread.currentThread().getName()+" waiting for commands!");
        while(true){
            try{
                Socket clientSocket = commandSocket.accept();
                InputStream inputStream = clientSocket.getInputStream();
                OutputStream outputStream = clientSocket.getOutputStream();
                byte[] buffer = new byte[1024];
                int bytesRead;
                if ((bytesRead = inputStream.read(buffer)) != -1) {
                    String requestData = new String(buffer, 0, bytesRead);
                    if(requestData.startsWith(Command.CONNECT)){
                        int port = Integer.parseInt(requestData.trim().split("@")[1]);
                        outputStream.write((Command.OK+"@"+addClient(clientSocket,port)).getBytes());
                    }
                    else{
                        try{
                            String[] arrayString = requestData.trim().split("@");
                            String command = arrayString[0];
                            String idClient = arrayString[1];
                            String payLoad = arrayString.length>=3?arrayString[2]:"";
                            if(filterRequest(clientSocket,idClient)){
                                new Thread(new ClientHandlerTCP(clientSocket,command,idClient,payLoad,this)).start();
                                continue;
                            }
                        }catch(Exception ex){
                            log("[#]Error:" + ex.getMessage() + " from [WatchDog]");
                            outputStream.write(Command.UNKNOW_COMMAND.getBytes());
                        }
                    } 
                }
                clientSocket.close();
            }catch(SocketException ex) {
                log("[#]Error:" + ex.getMessage() + " from [WatchDog]");
                log("..."+Thread.currentThread().getName()+" [Closed]");
                Thread.currentThread().stop();
            }catch(IOException ex){
                log("[#]Error:" + ex.getMessage() + " from [WatchDog]");
            }
        }
    }
    
    private void watchCat() {
        log("..."+Thread.currentThread().getName()+" waiting for Streaming!");
        recivePacket = new DatagramPacket(imageData, imageData.length);
        while(true){
            try{
                this.streamingSocket.receive(recivePacket);
                for(StreamGroup group: streamers){
                    if(group.getHost().getAddr().equals(recivePacket.getAddress())){
                        if(group.getHost().getPort()==recivePacket.getPort()){
                            byteArrayInputStream = new ByteArrayInputStream(recivePacket.getData());
                            group.setCurrentImage(ImageIO.read(byteArrayInputStream));
                            ////////////////
                            for(Client c : group.getViewers()){
                                System.out.println(c.toString());
                                sendPacket = new DatagramPacket(recivePacket.getData(), recivePacket.getData().length,c.getAddr(),c.getPort());
                                streamingSocket.send(sendPacket);
                            }
                            
                        }
                    }
                    
                }
            }catch(SocketException ex) {
                log("[#]Error:" + ex.getMessage() + " from [WatchCat]");
                log("..."+Thread.currentThread().getName()+" [Closed]");
                Thread.currentThread().stop();
            }catch(IOException ex){
                log("[#]Error:" + ex.getMessage() + " from [WatchCat]");
            }
        }
    }
    
    private boolean filterRequest(Socket clientSocket,String idClient){
        return clients.stream()
                .anyMatch((client) -> (client.getAddr().equals(clientSocket.getInetAddress())
                        &&client.getId().equals(idClient)));
    }
    
    private void closeServer() {
        this.running = false;
        clients = null;
        streamers = null;
        this.btnAction.setText(START_SERVER);
        try{
            if(commandSocket!=null){
                commandSocket.close();
                commandSocket = null;
            }
            if(streamingSocket!=null){
                streamingSocket.close();
                streamingSocket = null;
            }
            log("[*]Server stopped!");
        }catch(IOException ex){
            log(ex.getMessage());
        }
    }
    
    public String addClient(Socket clientSocket,int portUDPClient){
        String id = UUID.randomUUID().toString();
        clients.add(new Client(id, clientSocket.getInetAddress(), portUDPClient));
        this.lbClients.setText(Integer.toString(clients.size()));
        log("["+clientSocket.getInetAddress()+"]["+portUDPClient+"] connected!");
        return id;
    }
    
    private void refreshLiveStreamPanel(){
        for(StreamGroup sg : streamers){
            boolean alreadyAdded = false;
            String IDLive = sg.getHost().getId();
            for (Component component : pnLiveStream.getComponents()) {
                if (component instanceof JPanel && component.getName() != null && component.getName().equals(IDLive)) {
                    alreadyAdded = true;
                    break;
                }
            }
            if(!alreadyAdded){
                Button button = new Button();
                button.setLabel(sg.getName());
                MainFrm mainFrmRef = this;
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        mainFrmRef.setVisible(false);
                        new StreamingFrm(mainFrmRef,sg).setVisible(true);
                    }
                });
                ImageIcon originalIcon = new ImageIcon(sg.getCurrentImage());
                Image scaledImage = originalIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                JLabel liveGroup = new JLabel(scaledIcon);
                JPanel panelPanel = new JPanel();
                panelPanel.setName(IDLive);
                panelPanel.add(liveGroup);
                panelPanel.add(button);
                this.pnLiveStream.add(panelPanel);
//                this.pnLiveStream.add(button);
            }
        }
        this.pnLiveStream.revalidate();
        this.pnLiveStream.repaint();
    }
    
    private void removeLiveNode(String IDLive) {
        for (Component component : pnLiveStream.getComponents()) {
            if (component instanceof JPanel && component.getName() != null && component.getName().equals(IDLive)) {
                pnLiveStream.remove(component);
                pnLiveStream.revalidate();
                pnLiveStream.repaint();
                break; // Bạn có thể xóa nhiều button có cùng tên, nếu muốn xóa toàn bộ, loại bỏ break.
            }
        }
    }
    
    private void removeAllButton () {
        for (Component component : pnLiveStream.getComponents()) {
            if (component instanceof JPanel && component.getName() != null) {
                pnLiveStream.remove(component);
                pnLiveStream.revalidate();
                pnLiveStream.repaint();
            }
        }
    }
    
    private String informationClient(String id){
        return "["+id.substring(0, 10)+"...]";
    }
    
    public int logoutClient(String clientId){
        MainFrm.clients = MainFrm.clients.stream()
                            .filter(c->!c.getId().equals(clientId))
                                .collect(Collectors.toList());
        log(this.informationClient(clientId)+ "disconnected!");
        this.lbClients.setText(Integer.toString(clients.size()));
        return 1;
    }
    
    public int addLiveGroup(String clientId,String name){
        Client host = clients.stream().filter(p->p.getId().equals(clientId)).findFirst().orElse(null);
        StreamGroup newHost = new StreamGroup(host,name);
        streamers.add(newHost);
        
        Runnable addButtonTask = () -> addButton(newHost);
        Thread addButtonThread = new Thread(addButtonTask);
        addButtonThread.setName("[AddLive]"+name);
        addButtonThread.start();
        
//        this.refreshLiveStreamPanel();
        log(this.informationClient(clientId)+ "opened live!");
        return 1;
    }
    
    public List<GroupLive> getListStream() {
        List<GroupLive> listLive = new ArrayList<>();
        ByteArrayOutputStream arrayOutputStream = new ByteArrayOutputStream();
        for(StreamGroup sg: MainFrm.streamers){
            if(sg.getCurrentImage()!=null){
                try{
                    ImageIO.write(sg.getCurrentImage(), "PNG", arrayOutputStream);
                    listLive.add(new GroupLive(sg.getHost(), sg.getName(), sg.getViewers().size(),arrayOutputStream.toByteArray()));
                }catch(IOException ex){
                    
                }
            }
        }
        return listLive;
    }
    
    public int linkStream(String clientId,String hostId){
        StreamGroup streamGroup = streamers.stream().filter(p->p.getHost().getId().equals(hostId)).findFirst().orElse(null);
        if(streamGroup!=null){
            Client client =clients.stream().filter(c->c.getId().equals(clientId)).findFirst().orElse(null);
            if(client != null){
                streamGroup.addViewer(client);
                return 1;
            }
        }
        return 0;
    }
    
    public int unLinkStream(String clientId,String hostId) {
        StreamGroup streamGroup = streamers.stream().filter(p->p.getHost().getId().equals(hostId)).findFirst().orElse(null);
        if(streamGroup!=null){
            Client client =clients.stream().filter(c->c.getId().equals(clientId)).findFirst().orElse(null);
            if(client != null){
                streamGroup.getViewers().remove(client);
//                streamGroup.addViewer(client);
                return 1;
            }
        }
        return 0;
    }
    
    public void addButton(StreamGroup newHost){
        while(newHost.getCurrentImage()==null){
            try{
                System.out.println("NOT DATA IMAGE");
                Thread.sleep(1000);
            }catch(InterruptedException ex){
                log(ex.getMessage()+" from " + Thread.currentThread().getName());
            }
        }
        String StreamID = newHost.getHost().getId();
        Button button = new Button();
        button.setName(StreamID);
        button.setLabel(newHost.getName());
        MainFrm mainFrmRef = this;
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrmRef.setVisible(false);
                new StreamingFrm(mainFrmRef,newHost).setVisible(true);
            }
        });
        ImageIcon originalIcon = new ImageIcon(newHost.getCurrentImage());
        Image scaledImage = originalIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        JLabel liveGroup = new JLabel(scaledIcon);
        
        JPanel labelPanel = new JPanel();
        labelPanel.add(liveGroup);
        labelPanel.add(button);
        labelPanel.setName(StreamID);
        this.pnLiveStream.add(labelPanel);
//                this.pnLiveStream.add(button);
        this.pnLiveStream.revalidate();
        this.pnLiveStream.repaint();
    }
    
    public int removeLiveGroup(String clientId,String name){
        this.streamers = MainFrm.streamers.stream()
                .filter(c->!c.getHost().getId().equals(clientId)).collect(Collectors.toList());
        this.removeLiveNode(clientId);
        log(this.informationClient(clientId)+ "offed stream!");
        return 1;
    }
    
    public void log(String log){
        this.txtLogs.append(log+"\n");
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClients;
    private javax.swing.JLabel lbDownload;
    private javax.swing.JLabel lbLineD;
    private javax.swing.JLabel lbLineU;
    private javax.swing.JLabel lbUpload;
    private javax.swing.JPanel pnLiveStream;
    private javax.swing.JTextArea txtLogs;
    // End of variables declaration//GEN-END:variables
}
